{{- $webAnnotations := .Values.service.annotations }}
{{- if .Values.gkeEndpoint.enabled }}
{{- $webAnnotations = omit $webAnnotations "cloud.google.com/neg" "cloud.google.com/backend-config" }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsrabbit.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opsrabbit.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.servicePort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "opsrabbit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsrabbit.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opsrabbit.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- if or .Values.service.annotations .Values.gkeEndpoint.enabled }}
  annotations:
    {{- with $webAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.gkeEndpoint.enabled }}
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/backend-config: '{"default":"{{ include "opsrabbit.fullname" . }}"}'
    {{- end }}
  {{- end }}
spec:
  type: {{ if .Values.gkeEndpoint.enabled }}ClusterIP{{ else }}{{ .Values.service.type }}{{ end }}
  ports:
    - name: http
      port: {{ .Values.web.servicePort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "opsrabbit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
