apiVersion: v2
name: opsrabbit
description: OpsRabbit web and backend workloads for Kubernetes and GKE
type: application
version: 0.2.3
appVersion: "1.0.0"
keywords:
  - opsrabbit
  - gke
  - kubernetes
maintainers:
  - name: OpsRabbit
